### ISSUE TITLE
page views from GA data

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/recommender_issues#12]
1 day, 7 day, 1 month, 1 yr page views for a given article based on GA data.

Option 1 - Computationally heavy, but generic
Use the user browsing history data itself.
```
def pageviews(articleId,starttime,endtime):
    some code here
```

Option 2 - Computationally faster, but less modular.
Use GA's inbuilt reporting functionality to return 1 day, 7 day etc pageviews (without user tracking).
We may have to use 4 JSONs to fetch report from google API and then process it into one file with counters as results.

I tend to lean towards option 2 for faster execution.
@rkuthiala, what is your take?

**Comment by rkuthiala** [comment]
Hi Dhaval,

Will go with your recommendations, option 2

**Comment by drdhaval2785** [comment]
script - pageviews.py
output - data/publisherId/viewcounter/[dmwy]

**Comment by rkuthiala** [comment]
Great ...

**Comment by drdhaval2785** [comment]
Sample output

```
{"/index/listview/category_id/epics": 16, "/index/detailview/book_id/kavyaprakaza-balabodhini": 1, "/index/listview/category_id/unpublished-books": 14, "/index/detailview/book_id/suvikrantavikramipariprccha": 2, "/index/listview/category_id/ganapati": 1, "/index/detailview/book_id/abhijjanazakuntala": 2, "/index/detailview/book_id/rgvedavedaggajyotis": 1, "/index/detailview/book_id/subhasitavali": 1}
```

**Comment by drdhaval2785** [comment]
@rkuthiala 
In request to your question on timestamp on whatsapp,
This is a typical input data

```
{"ga:pagePath":"\/index.php","ga:clientid":"1063984076.1478268805","ga:date":"20161104","ga:hour":"19","ga:minute":"43","ga:users":"1"}
```

pagePath - URL
clientId - unique ID
date
hour
minute
users - how many times he visited this page in that minute (usually 1, but may be 2-3 also)

**Comment by rkuthiala** [comment]
kool ..
