### ISSUE TITLE
For occurrences too apply stemmed version

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/recommender_issues#4]
Seems too difficult right now.
Can be attempted later on, if there is some proven improvement.

**Comment by drdhaval2785** [comment]
Right now we apply stemming in every possible case of English language.

**Comment by rkuthiala** [comment]
I've been able to find multiple indian language stemmers .. which i have forwarded to you on e-mail ... need to add hindi stemmer

**Comment by drdhaval2785** [comment]
Which stemmer? Link?
Already implemented and open sourced?

**Comment by rkuthiala** [comment]
i'll see the links again and forward multiple indian lang stemmer to you separately ...
