### ISSUE TITLE
review unique keywords/tags utility

### ISSUE THREAD

**Issue by rkuthiala** [drdhaval2785/recommender_issues#5]
review unique keywords/tags and its utility for recommendation system

**Comment by drdhaval2785** [comment]
@rkuthiala Nice to see you tracking issues here.
Use short title and write in the description part.

**Comment by drdhaval2785** [comment]
From the sample unique keywords analysis cursorily, it appears that they are mostly misspellings / website addresses / numbers etc. Not much of real information contained in them.
